name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Decode signing config
      shell: bash
      run: echo "${{secrets.SIGNING_CONFIG}}" | base64 --decode > "$GITHUB_WORKSPACE/signing_config.gradle"

    - name: Decode signing key
      shell: bash
      run: echo "${{secrets.SIGNING_KEY}}" | base64 --decode > "$GITHUB_WORKSPACE/signing_key.jks"

    - name: Cache gradle-wrapper
      uses: actions/cache@v2
      env:
        cache-name: gradle-wrapper-cache
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    - name: Cache gradle-cache
      uses: actions/cache@v2
      env:
        cache-name: gradle-cache
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('constants.gradle') }}

    - name: Allow executing gradlew
      run: chmod +rwx ./gradlew

    - name: Build-debug
      run: ./gradlew assembleDebug --parallel --build-cache

    - name: Upload Debug APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Build-release
      if: github.ref_type == 'tag'
      run: ./gradlew assembleRelease --parallel --build-cache

    - name: Upload Release APK
      if: github.ref_type == 'tag'
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk

